{ pkgs }: {
  deps = [
    pkgs.libffi
    pkgs.zlib
    pkgs.tk
    pkgs.tcl
    pkgs.openjpeg
    pkgs.libxcrypt
    pkgs.libwebp
    pkgs.libtiff
    pkgs.libjpeg
    pkgs.libimagequant
    pkgs.lcms2
    pkgs.freetype
    pkgs.pango
    pkgs.harfbuzz
    pkgs.glib
    pkgs.fontconfig
    pkgs.rustc
    pkgs.libiconv
    pkgs.cargo
    pkgs.cacert
    pkgs.glibcLocales
    pkgs.pkg-config
    pkgs.arrow-cpp
    pkgs.ghostscript
    pkgs.ffmpeg
  ];
}
